version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - npm install
      - export BUCKET=test-lambda-pipelines
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file output.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - output.yaml